locator_button_catalog = ".header-nav-search-input"
locator_button_find = '.fa-search'
locator_button_basket = 'xpath = //a[@href="/perchatki-i-nakladki-dlya-ruk/boksyorskie-perchatki/boksyorskie-perchatki-cliff-pvc-krasnogo-tsveta/"]'
locator_buy = 'span.button-fastorder__sk-oneclick:nth-child(1)'
locator_lastname = 'xpath = //input[@name="customer[lastname]"]'
locator_firstname = 'xpath = //input[@name="customer[firstname]"]'
locator_email = 'xpath = //input[@name="customer[email]"]'
locator_phone = 'xpath = //input[@name="customer[phone]"]'
locator_ok = '.shop-sk-oneclick__submit'
locator_kimono_1 = 'li.sidebar-cats_el:nth-child(4) > a:nth-child(2) > div:nth-child(2)'
locator_kimono = 'div.js-cat-subs-disclosed:nth-child(3) > a:nth-child(2) > div:nth-child(2)'
locator_comparison_kim = 'div.products-list_item:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > span:nth-child(2) > span:nth-child(2)'
locator_comparison_kim1 = 'div.products-list_item:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > span:nth-child(2) > span:nth-child(2)'
locator_comparison = 'div.aside-wrap_bottom:nth-child(2)'
locator_sort = '.js-select-toggle > a:nth-child(1)'
locator_sort1 = '.js-select-items > li:nth-child(3) > a:nth-child(1)'
locator_clothe1 = '//*[@id="main-content"]/div[3]/div/ul/li[5]/a'
locator_clothe = 'div.js-cat-subs-disclosed:nth-child(4) > a:nth-child(2) > div:nth-child(2)'
locator_hats1 = 'xpath = //a[@class="js-category-link" and @href="/odezhda/shapki/"]'
locator_a_cap = 'xpath = //a[@href="/odezhda/shapki/shapka-trowdown-krasnyy-seryy-chernyy/"]'
locator_hats = 'li.sidebar-cats_el:nth-child(4) > ul:nth-child(3) > li:nth-child(3) > a:nth-child(1)'
locator_kimono_karate = 'li.category-subcat-icon_item:nth-child(5) > div:nth-child(2) > a:nth-child(1)'
locator_kimono1 = 'xpath = //a[@class="js-category-link" and @href="/kimono/"]'
locator_rash = 'div.cat-menu__el:nth-child(5) > a:nth-child(1) > div:nth-child(2)'
locator_rash1 = 'div.cat-menu__el:nth-child(6) > a:nth-child(1) > div:nth-child(2)'
locator_date = '.js-select-items > li:nth-child(5) > a:nth-child(1)'
locator_rash_child = 'xpath = //a[@href="/rashgardy/1984/"]'
locator_in_basket = 'span.button:nth-child(4)'
locator_basket = '.header_cart-content'
locator_delete_basket = '.fa-minus-circle'
locator_logo = '#logo'
locator_clothe_season = 'div.js-cat-subs-disclosed:nth-child(4) > a:nth-child(2) > div:nth-child(2)'
locator_clothe_season1 = 'div.js-cat-subs-disclosed:nth-child(5) > a:nth-child(2) > div:nth-child(2)'
locator_t_shirts = 'li.category-subcat-icon_item:nth-child(1) > div:nth-child(2) > a:nth-child(1)'
locator_field_1 = 'input.js-number:nth-child(1)'
locator_field_2 = 'input.js-number:nth-child(2)'
locator_Manto = 'div.js-filter-item:nth-child(2) > div:nth-child(2) > label:nth-child(5) > a:nth-child(2)'
locator_size_l = 'label.filter-item_opts-el:nth-child(12) > span:nth-child(1) > input:nth-child(1)'
locator_all_size = 'div.filter-item_opts-el:nth-child(19) > span:nth-child(1)'
locator_show = 'input.bg-bs-color'
locator_reset = '.filter-reset'
locator_plus_favourites = 'xpath = //span[@class="pr-action-text"]'
locator_favourites = 'span.link.custom-pr_title'
locator_clear_favourites = '.js-clear-pr-list'
locator_plus = '.fa-caret-right'
locator_cupon = '.shop-sk-oneclick-final__coupon-link'
locator_field_cupon = '.shop-sk-oneclick-final__coupon-input'
locator_ok_cupon = '.shop-sk-oneclick-final__coupon-apply'